apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: infra-bujosa
  name: influxdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1024Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: infra-bujosa
  name: grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
